/**
 * Demo/Mock Data for Application Tracking & Disbursement
 * Used until backend endpoints are integrated
 */

// ─── Application Workflow Stages ───
export const WORKFLOW_STAGES = [
  { id: 1, name: "Application Submitted", role: "Applicant" },
  { id: 2, name: "Document Verification", role: "Data Entry Operator" },
  { id: 3, name: "Field Investigation", role: "Field Officer" },
  { id: 4, name: "Eligibility Assessment", role: "Block Dev. Officer" },
  { id: 5, name: "Sanctioning Authority", role: "District Collector" },
  { id: 6, name: "Fund Release", role: "Treasury Officer" },
];

// ─── Demo Applications ───
export const DEMO_APPLICATIONS = [
  {
    id: "APP-2026-00147",
    applicantName: "Rajesh Kumar Patel",
    applicantPhone: "+91 98765 43210",
    aadhaar: "XXXX-XXXX-4521",
    state: "Madhya Pradesh",
    district: "Indore",
    schemeName: "PM-KISAN Samman Nidhi Yojana",
    schemeCategory: "Agriculture,Rural & Environment",
    appliedDate: "2026-05-15",
    amount: "₹6,000/year",
    eligibilityScore: 92,
    currentStage: 5,
    status: "approved",
    stages: [
      { stage: 1, status: "completed", date: "2026-05-15", officer: null, remarks: "Online application submitted" },
      { stage: 2, status: "completed", date: "2026-05-17", officer: "Smt. Kavita Sharma", designation: "DEO, Indore", remarks: "All documents verified — Land record, Aadhaar, Bank passbook valid" },
      { stage: 3, status: "completed", date: "2026-05-22", officer: "Shri Amit Verma", designation: "Patwari, Indore Tehsil", remarks: "Field visit completed. Land holding confirmed 2.5 acres" },
      { stage: 4, status: "completed", date: "2026-05-25", officer: "Shri R.K. Mishra", designation: "BDO, Indore Block", remarks: "Eligible under small farmer category. Score: 92/100" },
      { stage: 5, status: "completed", date: "2026-05-28", officer: "Dr. Pankaj Saxena, IAS", designation: "Collector, Indore", remarks: "Sanctioned. Fund release order issued." },
      { stage: 6, status: "completed", date: "2026-06-02", officer: "Shri Vinod Gupta", designation: "Treasury Officer", remarks: "₹2,000 (1st installment) credited to A/C XXXX4521" },
    ],
  },
  {
    id: "APP-2026-00203",
    applicantName: "Sunita Devi",
    applicantPhone: "+91 87654 32109",
    aadhaar: "XXXX-XXXX-7893",
    state: "Rajasthan",
    district: "Jaipur",
    schemeName: "Pradhan Mantri Awas Yojana – Gramin",
    schemeCategory: "Housing & Shelter",
    appliedDate: "2026-04-20",
    amount: "₹1,30,000",
    eligibilityScore: 78,
    currentStage: 4,
    status: "in_progress",
    stages: [
      { stage: 1, status: "completed", date: "2026-04-20", officer: null, remarks: "CSC center application" },
      { stage: 2, status: "completed", date: "2026-04-23", officer: "Shri Mahesh Meena", designation: "DEO, Jaipur Rural", remarks: "Documents verified. BPL card confirmed." },
      { stage: 3, status: "completed", date: "2026-04-30", officer: "Smt. Rekha Singh", designation: "Gram Sevak, Sanganer", remarks: "House site inspection done. No pucca house found." },
      { stage: 4, status: "in_progress", date: null, officer: "Shri Devendra Yadav", designation: "BDO, Sanganer Block", remarks: "Awaiting SECC data cross-verification" },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
  {
    id: "APP-2026-00089",
    applicantName: "Mohammed Ismail Khan",
    applicantPhone: "+91 99887 76655",
    aadhaar: "XXXX-XXXX-3367",
    state: "Uttar Pradesh",
    district: "Lucknow",
    schemeName: "Mudra Yojana – Shishu Loan",
    schemeCategory: "Business & Entrepreneurship",
    appliedDate: "2026-03-10",
    amount: "₹50,000",
    eligibilityScore: 45,
    currentStage: 3,
    status: "rejected",
    rejectionReason: "Applicant's existing loan (from SBI, ₹2,00,000) exceeds the threshold for Shishu category. Business plan does not demonstrate sufficient revenue to service both loans concurrently.",
    rejectionOfficer: "Shri Arun Kumar Srivastava",
    rejectionDesignation: "Branch Manager, Canara Bank, Lucknow",
    stages: [
      { stage: 1, status: "completed", date: "2026-03-10", officer: null, remarks: "Bank branch application" },
      { stage: 2, status: "completed", date: "2026-03-12", officer: "Smt. Priyanka Gupta", designation: "Clerk, Canara Bank", remarks: "KYC documents verified. Business address confirmed." },
      { stage: 3, status: "rejected", date: "2026-03-18", officer: "Shri Arun Kumar Srivastava", designation: "Branch Manager, Canara Bank", remarks: "REJECTED — Existing loan liability exceeds threshold. CIBIL score 620 (below 650 minimum)." },
      { stage: 4, status: "pending", date: null, officer: null, remarks: null },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
  {
    id: "APP-2026-00312",
    applicantName: "Lakshmi Narayanan",
    applicantPhone: "+91 94433 22110",
    aadhaar: "XXXX-XXXX-9012",
    state: "Tamil Nadu",
    district: "Coimbatore",
    schemeName: "National Scholarship Portal – Post Matric SC",
    schemeCategory: "Education & Learning",
    appliedDate: "2026-06-01",
    amount: "₹36,000/year",
    eligibilityScore: 88,
    currentStage: 3,
    status: "in_progress",
    stages: [
      { stage: 1, status: "completed", date: "2026-06-01", officer: null, remarks: "NSP online portal submission" },
      { stage: 2, status: "completed", date: "2026-06-04", officer: "Dr. K. Selvam", designation: "Nodal Officer, Anna University", remarks: "Academic records & caste certificate verified" },
      { stage: 3, status: "in_progress", date: null, officer: "Shri B. Ramachandran", designation: "DWO, Coimbatore", remarks: "Income verification pending from Tahsildar" },
      { stage: 4, status: "pending", date: null, officer: null, remarks: null },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
  {
    id: "APP-2026-00456",
    applicantName: "Priya Sharma",
    applicantPhone: "+91 88776 55443",
    aadhaar: "XXXX-XXXX-6543",
    state: "Maharashtra",
    district: "Pune",
    schemeName: "Ayushman Bharat – PM-JAY",
    schemeCategory: "Health & Wellness",
    appliedDate: "2026-06-10",
    amount: "₹5,00,000 cover",
    eligibilityScore: 95,
    currentStage: 5,
    status: "approved",
    stages: [
      { stage: 1, status: "completed", date: "2026-06-10", officer: null, remarks: "Hospital desk registration" },
      { stage: 2, status: "completed", date: "2026-06-10", officer: "Smt. Meena Patil", designation: "PMAM, Sassoon Hospital", remarks: "Aadhaar & ration card verified. SECC eligible." },
      { stage: 3, status: "completed", date: "2026-06-11", officer: "Dr. Suresh Jadhav", designation: "Medical Officer, Sassoon", remarks: "Medical condition verified. Pre-authorization submitted." },
      { stage: 4, status: "completed", date: "2026-06-11", officer: "System Auto-approval", designation: "AB-PMJAY Portal", remarks: "Auto-approved based on SECC + procedure code match" },
      { stage: 5, status: "completed", date: "2026-06-12", officer: "Dr. Rajesh Deshpande", designation: "CMS, Sassoon Hospital", remarks: "Treatment sanctioned. Cashless claim approved." },
      { stage: 6, status: "in_progress", date: null, officer: null, remarks: "Post-treatment claim settlement in process" },
    ],
  },
  {
    id: "APP-2026-00178",
    applicantName: "Gurpreet Singh",
    applicantPhone: "+91 97712 33445",
    aadhaar: "XXXX-XXXX-1234",
    state: "Punjab",
    district: "Amritsar",
    schemeName: "PM Fasal Bima Yojana",
    schemeCategory: "Agriculture,Rural & Environment",
    appliedDate: "2026-04-05",
    amount: "₹25,000 (claim)",
    eligibilityScore: 82,
    currentStage: 2,
    status: "in_progress",
    stages: [
      { stage: 1, status: "completed", date: "2026-04-05", officer: null, remarks: "Bank linked application via SBI" },
      { stage: 2, status: "in_progress", date: null, officer: "Shri Balwinder Singh", designation: "Agriculture Officer, Amritsar", remarks: "Crop damage assessment scheduled for next week" },
      { stage: 3, status: "pending", date: null, officer: null, remarks: null },
      { stage: 4, status: "pending", date: null, officer: null, remarks: null },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
  {
    id: "APP-2026-00567",
    applicantName: "Anita Kumari",
    applicantPhone: "+91 91234 56789",
    aadhaar: "XXXX-XXXX-8899",
    state: "Bihar",
    district: "Patna",
    schemeName: "Sukanya Samriddhi Yojana",
    schemeCategory: "Women and Child",
    appliedDate: "2026-05-01",
    amount: "₹1,000/month",
    eligibilityScore: 98,
    currentStage: 6,
    status: "approved",
    stages: [
      { stage: 1, status: "completed", date: "2026-05-01", officer: null, remarks: "Post office application" },
      { stage: 2, status: "completed", date: "2026-05-02", officer: "Shri Rajesh Prasad", designation: "Post Master, GPO Patna", remarks: "Birth certificate & guardian documents verified" },
      { stage: 3, status: "completed", date: "2026-05-03", officer: "Smt. Sushma Devi", designation: "Inspector Posts, Patna", remarks: "Address verification complete" },
      { stage: 4, status: "completed", date: "2026-05-04", officer: "System Auto-approval", designation: "India Post Banking System", remarks: "Age criteria met. Account eligible for opening." },
      { stage: 5, status: "completed", date: "2026-05-05", officer: "Shri K.P. Sharma", designation: "Sr. Supdt. of Post Offices", remarks: "Account sanctioned" },
      { stage: 6, status: "completed", date: "2026-05-06", officer: "System", designation: "India Post Payments Bank", remarks: "Account opened. SSY A/C No: 2026050100234" },
    ],
  },
  {
    id: "APP-2026-00234",
    applicantName: "Venkatesh Reddy",
    applicantPhone: "+91 96543 21098",
    aadhaar: "XXXX-XXXX-4567",
    state: "Telangana",
    district: "Hyderabad",
    schemeName: "Stand-Up India Scheme",
    schemeCategory: "Business & Entrepreneurship",
    appliedDate: "2026-03-20",
    amount: "₹10,00,000",
    eligibilityScore: 35,
    currentStage: 4,
    status: "rejected",
    rejectionReason: "The proposed business (food processing unit) already has a registered proprietorship by the applicant. Stand-Up India mandates first-time entrepreneurs in manufacturing/services/trading. Additionally, CIBIL report shows default on previous personal loan.",
    rejectionOfficer: "Smt. Padmavathi Rao",
    rejectionDesignation: "Lead District Manager, SBI Hyderabad",
    stages: [
      { stage: 1, status: "completed", date: "2026-03-20", officer: null, remarks: "SIDBI Stand-Up India portal" },
      { stage: 2, status: "completed", date: "2026-03-23", officer: "Shri Ravi Teja", designation: "Loan Officer, SBI Secundrabad", remarks: "Documents collected. Business plan received." },
      { stage: 3, status: "completed", date: "2026-03-28", officer: "Shri P. Narasimha", designation: "Field Officer, SBI", remarks: "Site visit done. Existing business found at same premises." },
      { stage: 4, status: "rejected", date: "2026-04-02", officer: "Smt. Padmavathi Rao", designation: "LDM, SBI Hyderabad", remarks: "REJECTED — Not a first-time entrepreneur. CIBIL score 580. Previous loan default ₹1.2L" },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
  {
    id: "APP-2026-00389",
    applicantName: "Fatima Begum",
    applicantPhone: "+91 93344 55667",
    aadhaar: "XXXX-XXXX-2211",
    state: "West Bengal",
    district: "Kolkata",
    schemeName: "PM Ujjwala Yojana 2.0",
    schemeCategory: "Utility & Sanitation",
    appliedDate: "2026-06-20",
    amount: "Free LPG Connection + ₹1,600",
    eligibilityScore: 90,
    currentStage: 1,
    status: "submitted",
    stages: [
      { stage: 1, status: "completed", date: "2026-06-20", officer: null, remarks: "LPG distributor application submitted with self-declaration" },
      { stage: 2, status: "pending", date: null, officer: null, remarks: null },
      { stage: 3, status: "pending", date: null, officer: null, remarks: null },
      { stage: 4, status: "pending", date: null, officer: null, remarks: null },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
  {
    id: "APP-2026-00501",
    applicantName: "Deepak Choudhary",
    applicantPhone: "+91 98112 34567",
    aadhaar: "XXXX-XXXX-6677",
    state: "Haryana",
    district: "Gurugram",
    schemeName: "Skill India – PMKVY 4.0",
    schemeCategory: "Skills & Employment",
    appliedDate: "2026-05-28",
    amount: "Free Training + ₹8,000 stipend",
    eligibilityScore: 85,
    currentStage: 4,
    status: "in_progress",
    stages: [
      { stage: 1, status: "completed", date: "2026-05-28", officer: null, remarks: "Online enrollment via Skill India portal" },
      { stage: 2, status: "completed", date: "2026-05-30", officer: "Smt. Nisha Tanwar", designation: "TP Coordinator, NSDC", remarks: "Aadhaar, education certificates verified" },
      { stage: 3, status: "completed", date: "2026-06-02", officer: "Shri Vikas Hooda", designation: "Assessment Officer, SSC", remarks: "Skill gap assessment completed. Recommended: Data Entry Operator course" },
      { stage: 4, status: "in_progress", date: null, officer: "Shri Rakesh Yadav", designation: "District Skill Officer, Gurugram", remarks: "Training center slot allocation in progress" },
      { stage: 5, status: "pending", date: null, officer: null, remarks: null },
      { stage: 6, status: "pending", date: null, officer: null, remarks: null },
    ],
  },
];

// ─── Demo Disbursement Records ───
export const DEMO_DISBURSEMENTS = [
  {
    id: "DISB-2026-0001",
    applicationId: "APP-2026-00147",
    beneficiary: "Rajesh Kumar Patel",
    scheme: "PM-KISAN Samman Nidhi",
    state: "Madhya Pradesh",
    totalAmount: 6000,
    disbursedAmount: 2000,
    pendingAmount: 4000,
    status: "partial",
    installments: [
      { no: 1, amount: 2000, date: "2026-06-02", status: "credited", txnId: "UTR-7829341", mode: "DBT" },
      { no: 2, amount: 2000, date: "2026-10-01", status: "scheduled", txnId: null, mode: "DBT" },
      { no: 3, amount: 2000, date: "2027-02-01", status: "scheduled", txnId: null, mode: "DBT" },
    ],
    milestones: [
      { name: "KYC Verification", completed: true, date: "2026-05-17" },
      { name: "Bank Account Seeding", completed: true, date: "2026-05-20" },
      { name: "1st Installment Release", completed: true, date: "2026-06-02" },
      { name: "Land Record Re-verification", completed: false, date: null },
      { name: "2nd Installment Release", completed: false, date: null },
      { name: "Annual Audit Compliance", completed: false, date: null },
    ],
  },
  {
    id: "DISB-2026-0002",
    applicationId: "APP-2026-00456",
    beneficiary: "Priya Sharma",
    scheme: "Ayushman Bharat PM-JAY",
    state: "Maharashtra",
    totalAmount: 180000,
    disbursedAmount: 0,
    pendingAmount: 180000,
    status: "processing",
    installments: [
      { no: 1, amount: 180000, date: null, status: "claim_submitted", txnId: null, mode: "Cashless" },
    ],
    milestones: [
      { name: "Pre-Authorization", completed: true, date: "2026-06-11" },
      { name: "Treatment Completed", completed: true, date: "2026-06-18" },
      { name: "Discharge Summary Upload", completed: true, date: "2026-06-18" },
      { name: "Claim Verification", completed: false, date: null },
      { name: "Settlement to Hospital", completed: false, date: null },
    ],
  },
  {
    id: "DISB-2026-0003",
    applicationId: "APP-2026-00567",
    beneficiary: "Anita Kumari",
    scheme: "Sukanya Samriddhi Yojana",
    state: "Bihar",
    totalAmount: 12000,
    disbursedAmount: 12000,
    pendingAmount: 0,
    status: "completed",
    installments: [
      { no: 1, amount: 1000, date: "2026-05-06", status: "credited", txnId: "PO-99812001", mode: "Post Office" },
      { no: 2, amount: 1000, date: "2026-06-01", status: "credited", txnId: "PO-99812045", mode: "Post Office" },
      { no: 3, amount: 1000, date: "2026-07-01", status: "credited", txnId: "PO-99812078", mode: "Post Office" },
    ],
    milestones: [
      { name: "Account Opening", completed: true, date: "2026-05-06" },
      { name: "Guardian KYC Complete", completed: true, date: "2026-05-06" },
      { name: "First Deposit", completed: true, date: "2026-05-06" },
      { name: "Standing Instruction Set", completed: true, date: "2026-05-10" },
      { name: "Quarterly Statement Generated", completed: true, date: "2026-07-01" },
    ],
  },
];

// ─── Status Colors & Labels ───
export const STATUS_CONFIG = {
  approved: { label: "Approved", color: "#16a34a", bg: "#dcfce7" },
  rejected: { label: "Rejected", color: "#dc2626", bg: "#fee2e2" },
  in_progress: { label: "In Progress", color: "#d97706", bg: "#fef3c7" },
  submitted: { label: "Submitted", color: "#7c3aed", bg: "#ede9fe" },
  partial: { label: "Partial", color: "#d97706", bg: "#fef3c7" },
  processing: { label: "Processing", color: "#0891b2", bg: "#ecfeff" },
  completed: { label: "Completed", color: "#16a34a", bg: "#dcfce7" },
  credited: { label: "Credited", color: "#16a34a", bg: "#dcfce7" },
  scheduled: { label: "Scheduled", color: "#7c3aed", bg: "#ede9fe" },
  claim_submitted: { label: "Claim Submitted", color: "#0891b2", bg: "#ecfeff" },
};
