from pymongo import MongoClient
MONGO_URI = "mongodb://keoteakash:Akash%40db123@cluster0-shard-00-00.jl5jf.mongodb.net:27017,cluster0-shard-00-01.jl5jf.mongodb.net:27017,cluster0-shard-00-02.jl5jf.mongodb.net:27017/subsidy_db?ssl=true&replicaSet=atlas-13g8ac-shard-0&authSource=admin&retryWrites=true&w=majority"

schemes = [
  {"title":"MGNREGA","description":"Guarantees 100 days of wage employment per year to rural households willing to do unskilled manual work.","amount":0,"eligibilityCriteria":"Any adult member of a rural household willing to do unskilled manual work.","applicationDeadline":"2030-12-31","state":"All States","category":"Employment","isActive":True},
  {"title":"Pradhan Mantri Gram Sadak Yojana","description":"All-weather road connectivity to unconnected habitations in rural areas.","amount":0,"eligibilityCriteria":"Unconnected rural habitations with population of 500+.","applicationDeadline":"2030-12-31","state":"All States","category":"Infrastructure","isActive":True},
  {"title":"Sarva Shiksha Abhiyan","description":"Universal elementary education for children aged 6-14 years ensuring free and compulsory education.","amount":0,"eligibilityCriteria":"All children aged 6-14 years.","applicationDeadline":"2030-12-31","state":"All States","category":"Education & Skill","isActive":True},
  {"title":"Mid-Day Meal Scheme (PM POSHAN)","description":"Free lunch on working days for children in government schools to improve nutritional levels.","amount":0,"eligibilityCriteria":"Children in Classes 1-8 in government and aided schools.","applicationDeadline":"2030-12-31","state":"All States","category":"Child Welfare","isActive":True},
  {"title":"National Rural Health Mission (NHM)","description":"Accessible, affordable, and quality healthcare for rural populations especially women and children.","amount":0,"eligibilityCriteria":"All rural citizens, priority to women and children.","applicationDeadline":"2030-12-31","state":"All States","category":"Healthcare","isActive":True},
  {"title":"Rashtriya Krishi Vikas Yojana","description":"Additional central assistance to incentivize states to increase public investment in agriculture.","amount":0,"eligibilityCriteria":"State governments and farming communities.","applicationDeadline":"2030-12-31","state":"All States","category":"Agriculture","isActive":True},
  {"title":"National Food Security Act (NFSA)","description":"Subsidized food grains at Rs 1-3/kg to approximately 81 crore people.","amount":0,"eligibilityCriteria":"Priority households and Antyodaya families identified by states.","applicationDeadline":"2030-12-31","state":"All States","category":"Food Security","isActive":True},
  {"title":"Sukanya Samriddhi Yojana","description":"Small deposit scheme for girl child with high interest rate and tax benefits.","amount":250,"eligibilityCriteria":"Parents of girl child below 10 years of age.","applicationDeadline":"2030-12-31","state":"All States","category":"Child Welfare","isActive":True},
  {"title":"Beti Bachao Beti Padhao","description":"Campaign to address declining child sex ratio and promote education for girls.","amount":0,"eligibilityCriteria":"Girl children across India.","applicationDeadline":"2030-12-31","state":"All States","category":"Child Welfare","isActive":True},
  {"title":"Skill India Mission (PMKVY)","description":"Short-term skill training with certification and monetary reward to youth.","amount":8000,"eligibilityCriteria":"Indian nationals aged 15-45 years.","applicationDeadline":"2026-12-31","state":"All States","category":"Education & Skill","isActive":True},
  {"title":"Digital India Programme","description":"Transform India into a digitally empowered society with digital infrastructure and governance.","amount":0,"eligibilityCriteria":"All Indian citizens and government departments.","applicationDeadline":"2030-12-31","state":"All States","category":"Digital Empowerment","isActive":True},
  {"title":"Startup India Initiative","description":"Action plan to promote startups with tax exemptions, easy compliance, and funding support.","amount":1000000,"eligibilityCriteria":"DPIIT-recognized startups incorporated as Pvt Ltd, LLP, or Partnership.","applicationDeadline":"2030-12-31","state":"All States","category":"Business","isActive":True},
  {"title":"PM Ujjwala Yojana 2.0","description":"Free LPG connections with first refill and stove to poor households.","amount":1600,"eligibilityCriteria":"Adult women from poor households not having LPG connection.","applicationDeadline":"2026-12-31","state":"All States","category":"Women Empowerment","isActive":True},
  {"title":"Ayushman Bharat Health Infrastructure Mission","description":"Develop health infrastructure including health and wellness centres across all districts.","amount":0,"eligibilityCriteria":"All districts, priority to aspirational districts.","applicationDeadline":"2026-12-31","state":"All States","category":"Healthcare","isActive":True},
  {"title":"PM Garib Kalyan Anna Yojana","description":"Free ration of 5kg food grains per person per month to 80 crore beneficiaries.","amount":0,"eligibilityCriteria":"All NFSA beneficiaries.","applicationDeadline":"2028-12-31","state":"All States","category":"Food Security","isActive":True},
  {"title":"Agnipath Scheme","description":"Short-term military recruitment for youth aged 17.5-23 with attractive pay and Seva Nidhi package.","amount":1176000,"eligibilityCriteria":"Indian citizens aged 17.5-23 years meeting physical/educational criteria.","applicationDeadline":"2030-12-31","state":"All States","category":"Employment","isActive":True},
  {"title":"PM SVANidhi","description":"Micro-credit facility of up to Rs 50000 to street vendors for working capital.","amount":50000,"eligibilityCriteria":"Street vendors with certificate of vending or letter of recommendation.","applicationDeadline":"2026-12-31","state":"All States","category":"Business","isActive":True},
  {"title":"National Education Policy Scheme","description":"Implementation of NEP 2020 with focus on multidisciplinary education and mother tongue instruction.","amount":0,"eligibilityCriteria":"All educational institutions and students across India.","applicationDeadline":"2030-12-31","state":"All States","category":"Education & Skill","isActive":True},
  {"title":"Maharashtra Rojgar Hami Yojana","description":"State extension of MGNREGA with additional 100 days employment guarantee.","amount":0,"eligibilityCriteria":"Rural households in Maharashtra.","applicationDeadline":"2026-12-31","state":"Maharashtra","category":"Employment","isActive":True},
  {"title":"Balasaheb Thackeray Smruti Matoshree Vriddhashram","description":"Old age home scheme for destitute senior citizens in Maharashtra.","amount":0,"eligibilityCriteria":"Senior citizens above 60 without family support.","applicationDeadline":"2026-12-31","state":"Maharashtra","category":"Social Security","isActive":True},
  {"title":"Amma Two Wheeler Scheme","description":"50% subsidy on purchase of two-wheelers for working women in Tamil Nadu.","amount":25000,"eligibilityCriteria":"Working women aged 18+ with annual income below Rs 2.5 Lakh.","applicationDeadline":"2026-12-31","state":"Tamil Nadu","category":"Women Empowerment","isActive":True},
  {"title":"YSR Rythu Bharosa","description":"Financial assistance of Rs 13500 per annum to farmer families for investment support.","amount":13500,"eligibilityCriteria":"All farmer families in AP holding cultivable land.","applicationDeadline":"2026-12-31","state":"Andhra Pradesh","category":"Agriculture","isActive":True},
  {"title":"Amma Vodi","description":"Rs 15000 per year to mothers/guardians for sending children to school.","amount":15000,"eligibilityCriteria":"Mothers below poverty line with children studying in Classes 1-12.","applicationDeadline":"2026-12-31","state":"Andhra Pradesh","category":"Education & Skill","isActive":True},
  {"title":"Kerala LIFE Mission","description":"Housing for all homeless and landless families with houses up to 400 sq ft.","amount":600000,"eligibilityCriteria":"Homeless families identified in life survey.","applicationDeadline":"2026-12-31","state":"Kerala","category":"Housing","isActive":True},
  {"title":"Kalia Scheme","description":"Financial assistance of Rs 25000 per farm family for cultivation and Rs 12500 for landless households.","amount":25000,"eligibilityCriteria":"Small and marginal farmers and landless agricultural households in Odisha.","applicationDeadline":"2026-12-31","state":"Odisha","category":"Agriculture","isActive":True},
  {"title":"Sambal Yojana","description":"Social security scheme covering life insurance, accident insurance, and utility bill subsidies for unorganized workers.","amount":0,"eligibilityCriteria":"Unorganized sector workers in MP registered under Sambal.","applicationDeadline":"2026-12-31","state":"Madhya Pradesh","category":"Social Security","isActive":True},
  {"title":"Krishi Ashirwad Yojana","description":"Rs 5000 per acre grant to small and marginal farmers per cropping season.","amount":25000,"eligibilityCriteria":"Farmers holding up to 5 acres of cultivable land.","applicationDeadline":"2026-12-31","state":"Jharkhand","category":"Agriculture","isActive":True},
  {"title":"Mukhyamantri Kisan Kalyan Yojana","description":"Additional Rs 4000 per year to PM-KISAN beneficiaries from state funds.","amount":4000,"eligibilityCriteria":"All PM-KISAN registered farmers in MP.","applicationDeadline":"2026-12-31","state":"Madhya Pradesh","category":"Agriculture","isActive":True},
  {"title":"Har Ghar Nal Yojana (Gujarat)","description":"Piped water connection to every rural household in Gujarat.","amount":0,"eligibilityCriteria":"Rural households without piped water supply.","applicationDeadline":"2026-12-31","state":"Gujarat","category":"Basic Amenities","isActive":True},
  {"title":"Vahli Dikri Yojana","description":"Financial assistance at 3 stages of girl's education: Rs 4000, Rs 6000 and Rs 100000.","amount":110000,"eligibilityCriteria":"First two daughters of families with income below Rs 2 Lakh/year.","applicationDeadline":"2026-12-31","state":"Gujarat","category":"Child Welfare","isActive":True},
  {"title":"Nand Ghar Yojana","description":"Model Anganwadi centres with digital learning, solar panels, and nutrition for children.","amount":0,"eligibilityCriteria":"Children aged 0-6 years and pregnant/lactating women.","applicationDeadline":"2026-12-31","state":"All States","category":"Child Welfare","isActive":True},
  {"title":"Bangla Awas Yojana","description":"Financial assistance for construction of houses for homeless families.","amount":120000,"eligibilityCriteria":"Homeless families in West Bengal not covered under PMAY.","applicationDeadline":"2026-12-31","state":"West Bengal","category":"Housing","isActive":True},
  {"title":"Punjab Ashirwad Scheme","description":"Financial grant of Rs 21000 to SC girls at the time of marriage.","amount":21000,"eligibilityCriteria":"SC families with annual income below Rs 32790 for rural and Rs 38570 for urban.","applicationDeadline":"2026-12-31","state":"Punjab","category":"Women Empowerment","isActive":True},
  {"title":"Mukhyamantri Rajshri Yojana","description":"Rs 50000 in installments for girls born after June 2016 for health and education.","amount":50000,"eligibilityCriteria":"Girls born in govt hospitals after 01-06-2016.","applicationDeadline":"2026-12-31","state":"Rajasthan","category":"Child Welfare","isActive":True},
  {"title":"Kalyana Lakshmi / Shaadi Mubarak","description":"Rs 100116 financial assistance to BPL families for daughter's marriage.","amount":100116,"eligibilityCriteria":"BPL families in Telangana with daughters aged 18+.","applicationDeadline":"2026-12-31","state":"Telangana","category":"Women Empowerment","isActive":True},
  {"title":"Basava Vasati Yojana","description":"Housing scheme providing Rs 1.2-1.5 Lakh for house construction.","amount":150000,"eligibilityCriteria":"Homeless families in Karnataka not covered under other housing schemes.","applicationDeadline":"2026-12-31","state":"Karnataka","category":"Housing","isActive":True},
  {"title":"Mukhyamantri Abhyudaya Yojana","description":"Free coaching for competitive exams (UPSC, JEE, NEET) through online and offline mode.","amount":0,"eligibilityCriteria":"Students from economically weaker sections in UP.","applicationDeadline":"2026-12-31","state":"Uttar Pradesh","category":"Education & Skill","isActive":True},
  {"title":"Mukhyamantri Bal Seva Yojana","description":"Rs 4000/month and free education for children orphaned due to COVID or other calamities.","amount":4000,"eligibilityCriteria":"Children who lost parents/guardians.","applicationDeadline":"2026-12-31","state":"Uttar Pradesh","category":"Child Welfare","isActive":True},
  {"title":"Nethanna Nestham","description":"Rs 24000 per year financial assistance to handloom weavers.","amount":24000,"eligibilityCriteria":"Registered handloom weavers in Telangana.","applicationDeadline":"2026-12-31","state":"Telangana","category":"Employment","isActive":True},
  {"title":"Matsya Sampada Yojana","description":"Development of fisheries sector with infrastructure, insurance and training support.","amount":0,"eligibilityCriteria":"Fishermen, fish farmers, fish workers and fish vendors.","applicationDeadline":"2026-12-31","state":"All States","category":"Agriculture","isActive":True},
  {"title":"Samagra Shiksha Abhiyan","description":"Integrated scheme covering school education from pre-school to Class 12.","amount":0,"eligibilityCriteria":"All students in government and aided schools.","applicationDeadline":"2030-12-31","state":"All States","category":"Education & Skill","isActive":True},
  {"title":"Har Ghar Tiranga","description":"Free national flags and patriotic campaign under Azadi Ka Amrit Mahotsav.","amount":0,"eligibilityCriteria":"All Indian households.","applicationDeadline":"2026-08-15","state":"All States","category":"Social Welfare","isActive":True},
  {"title":"Himachal Grihini Suvidha Yojana","description":"Free LPG connections to BPL women in Himachal Pradesh.","amount":1600,"eligibilityCriteria":"BPL women without LPG connection.","applicationDeadline":"2026-12-31","state":"Himachal Pradesh","category":"Women Empowerment","isActive":True},
  {"title":"Uttarakhand Vatsalya Yojana","description":"Financial support and education for children orphaned during COVID.","amount":3000,"eligibilityCriteria":"Children who lost parents during COVID pandemic.","applicationDeadline":"2026-12-31","state":"Uttarakhand","category":"Child Welfare","isActive":True},
  {"title":"Goa Laadli Laxmi Scheme","description":"Rs 1 Lakh fixed deposit for girl child born after 2012 in Goa.","amount":100000,"eligibilityCriteria":"Girl children born to Goan domicile families.","applicationDeadline":"2026-12-31","state":"Goa","category":"Child Welfare","isActive":True},
  {"title":"Tripura Mukhyamantri Yuba Yogayog Yojana","description":"Free smartphones to youth for digital empowerment.","amount":10000,"eligibilityCriteria":"Youth aged 18-40 in Tripura.","applicationDeadline":"2026-12-31","state":"Tripura","category":"Digital Empowerment","isActive":True},
  {"title":"Manipur StartUp Scheme","description":"Financial support up to Rs 20 Lakh for innovative startups in Manipur.","amount":2000000,"eligibilityCriteria":"Registered startups in Manipur with innovative business ideas.","applicationDeadline":"2026-12-31","state":"Manipur","category":"Business","isActive":True},
  {"title":"Meghalaya Restart Scheme","description":"Financial support for self-employment to COVID-affected workers.","amount":250000,"eligibilityCriteria":"Returning migrant workers and affected youth.","applicationDeadline":"2026-12-31","state":"Meghalaya","category":"Employment","isActive":True},
  {"title":"Nagaland SDG Vision 2030","description":"Multi-sectoral development covering education, health, and infrastructure.","amount":0,"eligibilityCriteria":"All citizens of Nagaland.","applicationDeadline":"2030-12-31","state":"Nagaland","category":"Infrastructure","isActive":True},
  {"title":"Mizoram Socio-Economic Development Policy","description":"Interest-free loans and subsidies for new enterprises.","amount":500000,"eligibilityCriteria":"Entrepreneurs and self-help groups in Mizoram.","applicationDeadline":"2026-12-31","state":"Mizoram","category":"Business","isActive":True},
  {"title":"Sikkim Garib Awas Yojana","description":"Housing assistance of Rs 5 Lakh for homeless BPL families.","amount":500000,"eligibilityCriteria":"BPL families without pucca house in Sikkim.","applicationDeadline":"2026-12-31","state":"Sikkim","category":"Housing","isActive":True},
  {"title":"Arunachal Rising Campaign","description":"Multi-sectoral campaign covering roads, education, healthcare in remote areas.","amount":0,"eligibilityCriteria":"All residents of remote areas in Arunachal Pradesh.","applicationDeadline":"2026-12-31","state":"Arunachal Pradesh","category":"Infrastructure","isActive":True},
  {"title":"J&K Mumkin Scheme","description":"Subsidized commercial vehicles for unemployed youth for livelihood.","amount":0,"eligibilityCriteria":"Unemployed youth aged 18-35 in J&K.","applicationDeadline":"2026-12-31","state":"Jammu & Kashmir","category":"Employment","isActive":True},
  {"title":"Haryana Kaushal Rozgar Nigam","description":"Outsourced government recruitment through transparent online portal.","amount":0,"eligibilityCriteria":"Haryana domicile candidates for contractual government positions.","applicationDeadline":"2026-12-31","state":"Haryana","category":"Employment","isActive":True},
  {"title":"Chhattisgarh Godhan Nyay Yojana","description":"Government purchase of cow dung at Rs 2/kg to promote organic farming.","amount":0,"eligibilityCriteria":"Cattle owners and farmers in Chhattisgarh.","applicationDeadline":"2026-12-31","state":"Chhattisgarh","category":"Agriculture","isActive":True}
]

client = MongoClient(MONGO_URI)
db = client['subsidy_db']
col = db['subsidies']
existing = [s['title'] for s in col.find({}, {'title': 1})]
added = 0
for s in schemes:
    if s['title'] not in existing:
        col.insert_one(s)
        added += 1
        print(f"  + {s['title']} ({s['state']})")
    else:
        print(f"  = SKIP: {s['title']}")
print(f"\nDone! Added {added} new schemes. Total in DB: {col.count_documents({})}")
client.close()
